name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:

  test:
    name: CI / Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test
        env:
          ALCHEMY_MAINNET_URL:  ${{ secrets.ALCHEMY_MAINNET_URL }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
